logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        web: INFO
    com:
      ccpay:
        server: INFO
server:
  port: 19000
  tomcat:
    uri-encoding: UTF-8
spring:
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: classpath:/static/templates/
    suffix: .ftl
  jackson:
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.36.65:3307/ifpay_ccpay?zeroDateTimeBehavior=convertToNull
    username: Y5/3kn9iehL4HcbrIvnz0KqqNvcDzPQ35epd0HieYqJPDqly0eQ9epfchC9tHHW5lHyN8j/XjonyceiH6OGgiQ==
    password: Y5/3kn9iehL4HcbrIvnz0KqqNvcDzPQ35epd0HieYqJPDqly0eQ9epfchC9tHHW5lHyN8j/XjonyceiH6OGgiQ==
    #druid连接池配置
    druid:
      #初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 300
      #配置获取连接等待超时的时间
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      #合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.100.31.205
    # Redis服务器连接端口
    port: 16376
    # Redis服务器连接密码（默认为空）
    password: ifValue@QA-Redis888@666
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 50
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 10
    # 连接超时时间（毫秒）
    timeout: 30000
    #锁过期时间（秒）
    keyExpired: 10

mybatis:
  type-aliases-package: com.agent.core.repository
  mapper-locations: classpath*:mapper/*Mapper.xml
management:
  security:
    enabled: false
url:
  smartmapiUrl: http://localhost:19029
  sendEmailUrl: http://47.100.40.74:18190/inAccess/email
  ssoUrl: http://47.100.40.74:19022
  ccpayServerUrl: http:47.100.40.74:19049
scheduleList:
  notify: 0,4,8,10,100,300,600
  queryTradeStatus: 0,1,2,3,4,5,6,7




