/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppRelease implements Serializable {

    private static final long serialVersionUID = 1678204502;

    private ULong         id;
    private Integer       status;
    private String        appType;
    private String        appVersion;
    private String        appAddress;
    private LocalDateTime effectTime;
    private String        updateDesc;
    private String        limitVersion;
    private LocalDateTime createdTime;
    private LocalDateTime updateTime;
    private String        creator;
    private String        modifier;
    private String        appId;

    public AppRelease() {}

    public AppRelease(AppRelease value) {
        this.id = value.id;
        this.status = value.status;
        this.appType = value.appType;
        this.appVersion = value.appVersion;
        this.appAddress = value.appAddress;
        this.effectTime = value.effectTime;
        this.updateDesc = value.updateDesc;
        this.limitVersion = value.limitVersion;
        this.createdTime = value.createdTime;
        this.updateTime = value.updateTime;
        this.creator = value.creator;
        this.modifier = value.modifier;
        this.appId = value.appId;
    }

    public AppRelease(
        ULong         id,
        Integer       status,
        String        appType,
        String        appVersion,
        String        appAddress,
        LocalDateTime effectTime,
        String        updateDesc,
        String        limitVersion,
        LocalDateTime createdTime,
        LocalDateTime updateTime,
        String        creator,
        String        modifier,
        String        appId
    ) {
        this.id = id;
        this.status = status;
        this.appType = appType;
        this.appVersion = appVersion;
        this.appAddress = appAddress;
        this.effectTime = effectTime;
        this.updateDesc = updateDesc;
        this.limitVersion = limitVersion;
        this.createdTime = createdTime;
        this.updateTime = updateTime;
        this.creator = creator;
        this.modifier = modifier;
        this.appId = appId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getAppType() {
        return this.appType;
    }

    public void setAppType(String appType) {
        this.appType = appType;
    }

    public String getAppVersion() {
        return this.appVersion;
    }

    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    public String getAppAddress() {
        return this.appAddress;
    }

    public void setAppAddress(String appAddress) {
        this.appAddress = appAddress;
    }

    public LocalDateTime getEffectTime() {
        return this.effectTime;
    }

    public void setEffectTime(LocalDateTime effectTime) {
        this.effectTime = effectTime;
    }

    public String getUpdateDesc() {
        return this.updateDesc;
    }

    public void setUpdateDesc(String updateDesc) {
        this.updateDesc = updateDesc;
    }

    public String getLimitVersion() {
        return this.limitVersion;
    }

    public void setLimitVersion(String limitVersion) {
        this.limitVersion = limitVersion;
    }

    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppRelease (");

        sb.append(id);
        sb.append(", ").append(status);
        sb.append(", ").append(appType);
        sb.append(", ").append(appVersion);
        sb.append(", ").append(appAddress);
        sb.append(", ").append(effectTime);
        sb.append(", ").append(updateDesc);
        sb.append(", ").append(limitVersion);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(creator);
        sb.append(", ").append(modifier);
        sb.append(", ").append(appId);

        sb.append(")");
        return sb.toString();
    }
}
