/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 资源
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MenuResource implements Serializable {

    private static final long serialVersionUID = 738209774;

    private Long      id;
    private String    resourceCode;
    private String    parent;
    private String    actionType;
    private String    actionParams;
    private String    name;
    private String    desc;
    private Short     priority;
    private String    icon;
    private Timestamp createdAt;
    private Timestamp updatedAt;
    private String    status;
    private String    defaultIsSelected;

    public MenuResource() {}

    public MenuResource(MenuResource value) {
        this.id = value.id;
        this.resourceCode = value.resourceCode;
        this.parent = value.parent;
        this.actionType = value.actionType;
        this.actionParams = value.actionParams;
        this.name = value.name;
        this.desc = value.desc;
        this.priority = value.priority;
        this.icon = value.icon;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.status = value.status;
        this.defaultIsSelected = value.defaultIsSelected;
    }

    public MenuResource(
        Long      id,
        String    resourceCode,
        String    parent,
        String    actionType,
        String    actionParams,
        String    name,
        String    desc,
        Short     priority,
        String    icon,
        Timestamp createdAt,
        Timestamp updatedAt,
        String    status,
        String    defaultIsSelected
    ) {
        this.id = id;
        this.resourceCode = resourceCode;
        this.parent = parent;
        this.actionType = actionType;
        this.actionParams = actionParams;
        this.name = name;
        this.desc = desc;
        this.priority = priority;
        this.icon = icon;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.status = status;
        this.defaultIsSelected = defaultIsSelected;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getResourceCode() {
        return this.resourceCode;
    }

    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode;
    }

    public String getParent() {
        return this.parent;
    }

    public void setParent(String parent) {
        this.parent = parent;
    }

    public String getActionType() {
        return this.actionType;
    }

    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    public String getActionParams() {
        return this.actionParams;
    }

    public void setActionParams(String actionParams) {
        this.actionParams = actionParams;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Short getPriority() {
        return this.priority;
    }

    public void setPriority(Short priority) {
        this.priority = priority;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDefaultIsSelected() {
        return this.defaultIsSelected;
    }

    public void setDefaultIsSelected(String defaultIsSelected) {
        this.defaultIsSelected = defaultIsSelected;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MenuResource (");

        sb.append(id);
        sb.append(", ").append(resourceCode);
        sb.append(", ").append(parent);
        sb.append(", ").append(actionType);
        sb.append(", ").append(actionParams);
        sb.append(", ").append(name);
        sb.append(", ").append(desc);
        sb.append(", ").append(priority);
        sb.append(", ").append(icon);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(status);
        sb.append(", ").append(defaultIsSelected);

        sb.append(")");
        return sb.toString();
    }
}
