/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 商户平台关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MerchantPlatform implements Serializable {

    private static final long serialVersionUID = -1697539013;

    private ULong         id;
    private String        merchantId;
    private String        platformCode;
    private Integer       status;
    private LocalDateTime createdDate;
    private LocalDateTime updateDate;
    private String        appId;

    public MerchantPlatform() {}

    public MerchantPlatform(MerchantPlatform value) {
        this.id = value.id;
        this.merchantId = value.merchantId;
        this.platformCode = value.platformCode;
        this.status = value.status;
        this.createdDate = value.createdDate;
        this.updateDate = value.updateDate;
        this.appId = value.appId;
    }

    public MerchantPlatform(
        ULong         id,
        String        merchantId,
        String        platformCode,
        Integer       status,
        LocalDateTime createdDate,
        LocalDateTime updateDate,
        String        appId
    ) {
        this.id = id;
        this.merchantId = merchantId;
        this.platformCode = platformCode;
        this.status = status;
        this.createdDate = createdDate;
        this.updateDate = updateDate;
        this.appId = appId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getMerchantId() {
        return this.merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    public String getPlatformCode() {
        return this.platformCode;
    }

    public void setPlatformCode(String platformCode) {
        this.platformCode = platformCode;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MerchantPlatform (");

        sb.append(id);
        sb.append(", ").append(merchantId);
        sb.append(", ").append(platformCode);
        sb.append(", ").append(status);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(appId);

        sb.append(")");
        return sb.toString();
    }
}
