/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 操作日志
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperationLog implements Serializable {

    private static final long serialVersionUID = -363362841;

    private Long      id;
    private String    belongToOrg;
    private String    ownToOrg;
    private String    operatorName;
    private String    operatorIp;
    private String    sessionToken;
    private String    actionGroup;
    private String    actionGroupName;
    private String    action;
    private String    actionName;
    private String    actionRequestParams;
    private String    actionResultParams;
    private String    actionResultMsg;
    private String    securityLevel;
    private Timestamp createdAt;

    public OperationLog() {}

    public OperationLog(OperationLog value) {
        this.id = value.id;
        this.belongToOrg = value.belongToOrg;
        this.ownToOrg = value.ownToOrg;
        this.operatorName = value.operatorName;
        this.operatorIp = value.operatorIp;
        this.sessionToken = value.sessionToken;
        this.actionGroup = value.actionGroup;
        this.actionGroupName = value.actionGroupName;
        this.action = value.action;
        this.actionName = value.actionName;
        this.actionRequestParams = value.actionRequestParams;
        this.actionResultParams = value.actionResultParams;
        this.actionResultMsg = value.actionResultMsg;
        this.securityLevel = value.securityLevel;
        this.createdAt = value.createdAt;
    }

    public OperationLog(
        Long      id,
        String    belongToOrg,
        String    ownToOrg,
        String    operatorName,
        String    operatorIp,
        String    sessionToken,
        String    actionGroup,
        String    actionGroupName,
        String    action,
        String    actionName,
        String    actionRequestParams,
        String    actionResultParams,
        String    actionResultMsg,
        String    securityLevel,
        Timestamp createdAt
    ) {
        this.id = id;
        this.belongToOrg = belongToOrg;
        this.ownToOrg = ownToOrg;
        this.operatorName = operatorName;
        this.operatorIp = operatorIp;
        this.sessionToken = sessionToken;
        this.actionGroup = actionGroup;
        this.actionGroupName = actionGroupName;
        this.action = action;
        this.actionName = actionName;
        this.actionRequestParams = actionRequestParams;
        this.actionResultParams = actionResultParams;
        this.actionResultMsg = actionResultMsg;
        this.securityLevel = securityLevel;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBelongToOrg() {
        return this.belongToOrg;
    }

    public void setBelongToOrg(String belongToOrg) {
        this.belongToOrg = belongToOrg;
    }

    public String getOwnToOrg() {
        return this.ownToOrg;
    }

    public void setOwnToOrg(String ownToOrg) {
        this.ownToOrg = ownToOrg;
    }

    public String getOperatorName() {
        return this.operatorName;
    }

    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    public String getOperatorIp() {
        return this.operatorIp;
    }

    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp;
    }

    public String getSessionToken() {
        return this.sessionToken;
    }

    public void setSessionToken(String sessionToken) {
        this.sessionToken = sessionToken;
    }

    public String getActionGroup() {
        return this.actionGroup;
    }

    public void setActionGroup(String actionGroup) {
        this.actionGroup = actionGroup;
    }

    public String getActionGroupName() {
        return this.actionGroupName;
    }

    public void setActionGroupName(String actionGroupName) {
        this.actionGroupName = actionGroupName;
    }

    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getActionName() {
        return this.actionName;
    }

    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    public String getActionRequestParams() {
        return this.actionRequestParams;
    }

    public void setActionRequestParams(String actionRequestParams) {
        this.actionRequestParams = actionRequestParams;
    }

    public String getActionResultParams() {
        return this.actionResultParams;
    }

    public void setActionResultParams(String actionResultParams) {
        this.actionResultParams = actionResultParams;
    }

    public String getActionResultMsg() {
        return this.actionResultMsg;
    }

    public void setActionResultMsg(String actionResultMsg) {
        this.actionResultMsg = actionResultMsg;
    }

    public String getSecurityLevel() {
        return this.securityLevel;
    }

    public void setSecurityLevel(String securityLevel) {
        this.securityLevel = securityLevel;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OperationLog (");

        sb.append(id);
        sb.append(", ").append(belongToOrg);
        sb.append(", ").append(ownToOrg);
        sb.append(", ").append(operatorName);
        sb.append(", ").append(operatorIp);
        sb.append(", ").append(sessionToken);
        sb.append(", ").append(actionGroup);
        sb.append(", ").append(actionGroupName);
        sb.append(", ").append(action);
        sb.append(", ").append(actionName);
        sb.append(", ").append(actionRequestParams);
        sb.append(", ").append(actionResultParams);
        sb.append(", ").append(actionResultMsg);
        sb.append(", ").append(securityLevel);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
