/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import java.io.Serializable;
import java.util.Date;

import javax.annotation.Generated;


/**
 * 组织
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Org implements Serializable {

    private static final long serialVersionUID = -939830638;

    private Long      id;
    private String    orgNo;
    private String    belongToOrg;
    private String    ownToOrg;
    private String    outOrgNo;
    private String    name;
    private String    nickName;
    private String    desc;
    private String    mobile;
    private String    email;
    private String    website;
    private String    type;
    private Short     level;
    private Short     maxLevel;
    private String    creatorCreateType;
    private String    creatorName;
    private Date createdAt;
    private Date updatedAt;
    private String    status;

    public Org() {}

    public Org(Org value) {
        this.id = value.id;
        this.orgNo = value.orgNo;
        this.belongToOrg = value.belongToOrg;
        this.ownToOrg = value.ownToOrg;
        this.outOrgNo = value.outOrgNo;
        this.name = value.name;
        this.nickName = value.nickName;
        this.desc = value.desc;
        this.mobile = value.mobile;
        this.email = value.email;
        this.website = value.website;
        this.type = value.type;
        this.level = value.level;
        this.maxLevel = value.maxLevel;
        this.creatorCreateType = value.creatorCreateType;
        this.creatorName = value.creatorName;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.status = value.status;
    }

    public Org(
        Long      id,
        String    orgNo,
        String    belongToOrg,
        String    ownToOrg,
        String    outOrgNo,
        String    name,
        String    nickName,
        String    desc,
        String    mobile,
        String    email,
        String    website,
        String    type,
        Short     level,
        Short     maxLevel,
        String    creatorCreateType,
        String    creatorName,
        Date createdAt,
        Date updatedAt,
        String    status
    ) {
        this.id = id;
        this.orgNo = orgNo;
        this.belongToOrg = belongToOrg;
        this.ownToOrg = ownToOrg;
        this.outOrgNo = outOrgNo;
        this.name = name;
        this.nickName = nickName;
        this.desc = desc;
        this.mobile = mobile;
        this.email = email;
        this.website = website;
        this.type = type;
        this.level = level;
        this.maxLevel = maxLevel;
        this.creatorCreateType = creatorCreateType;
        this.creatorName = creatorName;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.status = status;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrgNo() {
        return this.orgNo;
    }

    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo;
    }

    public String getBelongToOrg() {
        return this.belongToOrg;
    }

    public void setBelongToOrg(String belongToOrg) {
        this.belongToOrg = belongToOrg;
    }

    public String getOwnToOrg() {
        return this.ownToOrg;
    }

    public void setOwnToOrg(String ownToOrg) {
        this.ownToOrg = ownToOrg;
    }

    public String getOutOrgNo() {
        return this.outOrgNo;
    }

    public void setOutOrgNo(String outOrgNo) {
        this.outOrgNo = outOrgNo;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Short getLevel() {
        return this.level;
    }

    public void setLevel(Short level) {
        this.level = level;
    }

    public Short getMaxLevel() {
        return this.maxLevel;
    }

    public void setMaxLevel(Short maxLevel) {
        this.maxLevel = maxLevel;
    }

    public String getCreatorCreateType() {
        return this.creatorCreateType;
    }

    public void setCreatorCreateType(String creatorCreateType) {
        this.creatorCreateType = creatorCreateType;
    }

    public String getCreatorName() {
        return this.creatorName;
    }

    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Org (");

        sb.append(id);
        sb.append(", ").append(orgNo);
        sb.append(", ").append(belongToOrg);
        sb.append(", ").append(ownToOrg);
        sb.append(", ").append(outOrgNo);
        sb.append(", ").append(name);
        sb.append(", ").append(nickName);
        sb.append(", ").append(desc);
        sb.append(", ").append(mobile);
        sb.append(", ").append(email);
        sb.append(", ").append(website);
        sb.append(", ").append(type);
        sb.append(", ").append(level);
        sb.append(", ").append(maxLevel);
        sb.append(", ").append(creatorCreateType);
        sb.append(", ").append(creatorName);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
