/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;


/**
 * 收款账户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayeeAccount implements Serializable {

    private static final long serialVersionUID = -569685061;

    private BigInteger    perAmountMin;
    private ULong         id;
    private String        accountType;
    private String        accountAlias;
    private String        loginNo;
    private BigInteger    dayAmount;
    private BigInteger    perAmount;
    private BigInteger    tradeInterval;
    private LocalDateTime lastTradeDate;
    private String        localeIp;
    private BigInteger    crawlInterval;
    private Integer       isdeleted;
    private LocalDateTime createdDate;
    private LocalDateTime updateDate;
    private Integer       unpayLimit;
    private Integer       unqrcodeLimit;
    private String        merchantId;
    private String        appId;

    public PayeeAccount() {}

    public PayeeAccount(PayeeAccount value) {
        this.perAmountMin = value.perAmountMin;
        this.id = value.id;
        this.accountType = value.accountType;
        this.accountAlias = value.accountAlias;
        this.loginNo = value.loginNo;
        this.dayAmount = value.dayAmount;
        this.perAmount = value.perAmount;
        this.tradeInterval = value.tradeInterval;
        this.lastTradeDate = value.lastTradeDate;
        this.localeIp = value.localeIp;
        this.crawlInterval = value.crawlInterval;
        this.isdeleted = value.isdeleted;
        this.createdDate = value.createdDate;
        this.updateDate = value.updateDate;
        this.unpayLimit = value.unpayLimit;
        this.unqrcodeLimit = value.unqrcodeLimit;
        this.merchantId = value.merchantId;
        this.appId = value.appId;
    }

    public PayeeAccount(
        BigInteger    perAmountMin,
        ULong         id,
        String        accountType,
        String        accountAlias,
        String        loginNo,
        BigInteger    dayAmount,
        BigInteger    perAmount,
        BigInteger    tradeInterval,
        LocalDateTime lastTradeDate,
        String        localeIp,
        BigInteger    crawlInterval,
        Integer       isdeleted,
        LocalDateTime createdDate,
        LocalDateTime updateDate,
        Integer       unpayLimit,
        Integer       unqrcodeLimit,
        String        merchantId,
        String        appId
    ) {
        this.perAmountMin = perAmountMin;
        this.id = id;
        this.accountType = accountType;
        this.accountAlias = accountAlias;
        this.loginNo = loginNo;
        this.dayAmount = dayAmount;
        this.perAmount = perAmount;
        this.tradeInterval = tradeInterval;
        this.lastTradeDate = lastTradeDate;
        this.localeIp = localeIp;
        this.crawlInterval = crawlInterval;
        this.isdeleted = isdeleted;
        this.createdDate = createdDate;
        this.updateDate = updateDate;
        this.unpayLimit = unpayLimit;
        this.unqrcodeLimit = unqrcodeLimit;
        this.merchantId = merchantId;
        this.appId = appId;
    }

    public BigInteger getPerAmountMin() {
        return this.perAmountMin;
    }

    public void setPerAmountMin(BigInteger perAmountMin) {
        this.perAmountMin = perAmountMin;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getAccountType() {
        return this.accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public String getAccountAlias() {
        return this.accountAlias;
    }

    public void setAccountAlias(String accountAlias) {
        this.accountAlias = accountAlias;
    }

    public String getLoginNo() {
        return this.loginNo;
    }

    public void setLoginNo(String loginNo) {
        this.loginNo = loginNo;
    }

    public BigInteger getDayAmount() {
        return this.dayAmount;
    }

    public void setDayAmount(BigInteger dayAmount) {
        this.dayAmount = dayAmount;
    }

    public BigInteger getPerAmount() {
        return this.perAmount;
    }

    public void setPerAmount(BigInteger perAmount) {
        this.perAmount = perAmount;
    }

    public BigInteger getTradeInterval() {
        return this.tradeInterval;
    }

    public void setTradeInterval(BigInteger tradeInterval) {
        this.tradeInterval = tradeInterval;
    }

    public LocalDateTime getLastTradeDate() {
        return this.lastTradeDate;
    }

    public void setLastTradeDate(LocalDateTime lastTradeDate) {
        this.lastTradeDate = lastTradeDate;
    }

    public String getLocaleIp() {
        return this.localeIp;
    }

    public void setLocaleIp(String localeIp) {
        this.localeIp = localeIp;
    }

    public BigInteger getCrawlInterval() {
        return this.crawlInterval;
    }

    public void setCrawlInterval(BigInteger crawlInterval) {
        this.crawlInterval = crawlInterval;
    }

    public Integer getIsdeleted() {
        return this.isdeleted;
    }

    public void setIsdeleted(Integer isdeleted) {
        this.isdeleted = isdeleted;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public Integer getUnpayLimit() {
        return this.unpayLimit;
    }

    public void setUnpayLimit(Integer unpayLimit) {
        this.unpayLimit = unpayLimit;
    }

    public Integer getUnqrcodeLimit() {
        return this.unqrcodeLimit;
    }

    public void setUnqrcodeLimit(Integer unqrcodeLimit) {
        this.unqrcodeLimit = unqrcodeLimit;
    }

    public String getMerchantId() {
        return this.merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PayeeAccount (");

        sb.append(perAmountMin);
        sb.append(", ").append(id);
        sb.append(", ").append(accountType);
        sb.append(", ").append(accountAlias);
        sb.append(", ").append(loginNo);
        sb.append(", ").append(dayAmount);
        sb.append(", ").append(perAmount);
        sb.append(", ").append(tradeInterval);
        sb.append(", ").append(lastTradeDate);
        sb.append(", ").append(localeIp);
        sb.append(", ").append(crawlInterval);
        sb.append(", ").append(isdeleted);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(unpayLimit);
        sb.append(", ").append(unqrcodeLimit);
        sb.append(", ").append(merchantId);
        sb.append(", ").append(appId);

        sb.append(")");
        return sb.toString();
    }
}
