/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 平台表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Platform implements Serializable {

    private static final long serialVersionUID = 571953756;

    private ULong         id;
    private String        code;
    private String        name;
    private LocalDateTime createdDate;
    private LocalDateTime updateDate;
    private Integer       status;
    private String        appId;
    private String        qrcodeWay;

    public Platform() {}

    public Platform(Platform value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.createdDate = value.createdDate;
        this.updateDate = value.updateDate;
        this.status = value.status;
        this.appId = value.appId;
        this.qrcodeWay = value.qrcodeWay;
    }

    public Platform(
        ULong         id,
        String        code,
        String        name,
        LocalDateTime createdDate,
        LocalDateTime updateDate,
        Integer       status,
        String        appId,
        String        qrcodeWay
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.createdDate = createdDate;
        this.updateDate = updateDate;
        this.status = status;
        this.appId = appId;
        this.qrcodeWay = qrcodeWay;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getQrcodeWay() {
        return this.qrcodeWay;
    }

    public void setQrcodeWay(String qrcodeWay) {
        this.qrcodeWay = qrcodeWay;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Platform (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(status);
        sb.append(", ").append(appId);
        sb.append(", ").append(qrcodeWay);

        sb.append(")");
        return sb.toString();
    }
}
