/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrcodeUrl implements Serializable {

    private static final long serialVersionUID = -131163278;

    private Integer       id;
    private String        appId;
    private String        serviceType;
    private String        merchantNo;
    private String        payeeAccount;
    private String        qrcodeNum;
    private String        qrcodeUrl;
    private BigInteger    amount;
    private Integer       status;
    private LocalDateTime expireDate;
    private LocalDateTime lastDate;
    private LocalDateTime nextDate;
    private LocalDateTime createdDate;
    private LocalDateTime updateDate;

    public QrcodeUrl() {}

    public QrcodeUrl(QrcodeUrl value) {
        this.id = value.id;
        this.appId = value.appId;
        this.serviceType = value.serviceType;
        this.merchantNo = value.merchantNo;
        this.payeeAccount = value.payeeAccount;
        this.qrcodeNum = value.qrcodeNum;
        this.qrcodeUrl = value.qrcodeUrl;
        this.amount = value.amount;
        this.status = value.status;
        this.expireDate = value.expireDate;
        this.lastDate = value.lastDate;
        this.nextDate = value.nextDate;
        this.createdDate = value.createdDate;
        this.updateDate = value.updateDate;
    }

    public QrcodeUrl(
        Integer       id,
        String        appId,
        String        serviceType,
        String        merchantNo,
        String        payeeAccount,
        String        qrcodeNum,
        String        qrcodeUrl,
        BigInteger    amount,
        Integer       status,
        LocalDateTime expireDate,
        LocalDateTime lastDate,
        LocalDateTime nextDate,
        LocalDateTime createdDate,
        LocalDateTime updateDate
    ) {
        this.id = id;
        this.appId = appId;
        this.serviceType = serviceType;
        this.merchantNo = merchantNo;
        this.payeeAccount = payeeAccount;
        this.qrcodeNum = qrcodeNum;
        this.qrcodeUrl = qrcodeUrl;
        this.amount = amount;
        this.status = status;
        this.expireDate = expireDate;
        this.lastDate = lastDate;
        this.nextDate = nextDate;
        this.createdDate = createdDate;
        this.updateDate = updateDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getServiceType() {
        return this.serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public String getMerchantNo() {
        return this.merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    public String getPayeeAccount() {
        return this.payeeAccount;
    }

    public void setPayeeAccount(String payeeAccount) {
        this.payeeAccount = payeeAccount;
    }

    public String getQrcodeNum() {
        return this.qrcodeNum;
    }

    public void setQrcodeNum(String qrcodeNum) {
        this.qrcodeNum = qrcodeNum;
    }

    public String getQrcodeUrl() {
        return this.qrcodeUrl;
    }

    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl;
    }

    public BigInteger getAmount() {
        return this.amount;
    }

    public void setAmount(BigInteger amount) {
        this.amount = amount;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getExpireDate() {
        return this.expireDate;
    }

    public void setExpireDate(LocalDateTime expireDate) {
        this.expireDate = expireDate;
    }

    public LocalDateTime getLastDate() {
        return this.lastDate;
    }

    public void setLastDate(LocalDateTime lastDate) {
        this.lastDate = lastDate;
    }

    public LocalDateTime getNextDate() {
        return this.nextDate;
    }

    public void setNextDate(LocalDateTime nextDate) {
        this.nextDate = nextDate;
    }

    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QrcodeUrl (");

        sb.append(id);
        sb.append(", ").append(appId);
        sb.append(", ").append(serviceType);
        sb.append(", ").append(merchantNo);
        sb.append(", ").append(payeeAccount);
        sb.append(", ").append(qrcodeNum);
        sb.append(", ").append(qrcodeUrl);
        sb.append(", ").append(amount);
        sb.append(", ").append(status);
        sb.append(", ").append(expireDate);
        sb.append(", ").append(lastDate);
        sb.append(", ").append(nextDate);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(updateDate);

        sb.append(")");
        return sb.toString();
    }
}
