/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 角色
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = -1666855629;

    private Long      id;
    private String    roleNo;
    private String    parent;
    private String    category;
    private String    name;
    private String    desc;
    private Short     level;
    private String    status;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.roleNo = value.roleNo;
        this.parent = value.parent;
        this.category = value.category;
        this.name = value.name;
        this.desc = value.desc;
        this.level = value.level;
        this.status = value.status;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Role(
        Long      id,
        String    roleNo,
        String    parent,
        String    category,
        String    name,
        String    desc,
        Short     level,
        String    status,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.roleNo = roleNo;
        this.parent = parent;
        this.category = category;
        this.name = name;
        this.desc = desc;
        this.level = level;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRoleNo() {
        return this.roleNo;
    }

    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo;
    }

    public String getParent() {
        return this.parent;
    }

    public void setParent(String parent) {
        this.parent = parent;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Short getLevel() {
        return this.level;
    }

    public void setLevel(Short level) {
        this.level = level;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(roleNo);
        sb.append(", ").append(parent);
        sb.append(", ").append(category);
        sb.append(", ").append(name);
        sb.append(", ").append(desc);
        sb.append(", ").append(level);
        sb.append(", ").append(status);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
