/*
 * This file is generated by jOOQ.
*/
package com.agent.core.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 配置
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysConfig implements Serializable {

    private static final long serialVersionUID = 1538574893;

    private Long      id;
    private String    category;
    private String    key;
    private String    value;
    private Timestamp createdAt;
    private Timestamp updatedAt;
    private String    status;

    public SysConfig() {}

    public SysConfig(SysConfig value) {
        this.id = value.id;
        this.category = value.category;
        this.key = value.key;
        this.value = value.value;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.status = value.status;
    }

    public SysConfig(
        Long      id,
        String    category,
        String    key,
        String    value,
        Timestamp createdAt,
        Timestamp updatedAt,
        String    status
    ) {
        this.id = id;
        this.category = category;
        this.key = key;
        this.value = value;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.status = status;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysConfig (");

        sb.append(id);
        sb.append(", ").append(category);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
