/*
 * This file is generated by jOOQ.
*/
package com.agent.core.daos;


import com.agent.core.generated.tables.Merchant;
import com.agent.core.generated.tables.records.MerchantRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.time.LocalDateTime;
import java.util.List;


/**
 * 商户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MerchantDao extends DAOImpl<MerchantRecord, com.agent.core.pojos.Merchant, ULong> {

    /**
     * Create a new MerchantDao without any configuration
     */
    public MerchantDao() {
        super(Merchant.MERCHANT, com.agent.core.pojos.Merchant.class);
    }

    /**
     * Create a new MerchantDao with an attached configuration
     */
    public MerchantDao(Configuration configuration) {
        super(Merchant.MERCHANT, com.agent.core.pojos.Merchant.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.agent.core.pojos.Merchant object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchById(ULong... values) {
        return fetch(Merchant.MERCHANT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.agent.core.pojos.Merchant fetchOneById(ULong value) {
        return fetchOne(Merchant.MERCHANT.ID, value);
    }

    /**
     * Fetch records that have <code>MERCHANT_ID IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByMerchantId(String... values) {
        return fetch(Merchant.MERCHANT.MERCHANT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>MERCHANT_ID = value</code>
     */
    public com.agent.core.pojos.Merchant fetchOneByMerchantId(String value) {
        return fetchOne(Merchant.MERCHANT.MERCHANT_ID, value);
    }

    /**
     * Fetch records that have <code>MERCHANT_NAME IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByMerchantName(String... values) {
        return fetch(Merchant.MERCHANT.MERCHANT_NAME, values);
    }

    /**
     * Fetch records that have <code>LOGIN_NO IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByLoginNo(String... values) {
        return fetch(Merchant.MERCHANT.LOGIN_NO, values);
    }

    /**
     * Fetch records that have <code>ISDELETED IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByIsdeleted(Integer... values) {
        return fetch(Merchant.MERCHANT.ISDELETED, values);
    }

    /**
     * Fetch records that have <code>CREATED_TIME IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(Merchant.MERCHANT.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>UPDATE_TIME IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(Merchant.MERCHANT.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>SIGN_KEY IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchBySignKey(String... values) {
        return fetch(Merchant.MERCHANT.SIGN_KEY, values);
    }

    /**
     * Fetch records that have <code>MOBILE IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByMobile(String... values) {
        return fetch(Merchant.MERCHANT.MOBILE, values);
    }

    /**
     * Fetch records that have <code>EMAIL IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByEmail(String... values) {
        return fetch(Merchant.MERCHANT.EMAIL, values);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByAppId(String... values) {
        return fetch(Merchant.MERCHANT.APP_ID, values);
    }

    /**
     * Fetch records that have <code>note IN (values)</code>
     */
    public List<com.agent.core.pojos.Merchant> fetchByNote(String... values) {
        return fetch(Merchant.MERCHANT.NOTE, values);
    }
}
