/*
 * This file is generated by jOOQ.
*/
package com.agent.core.daos;


import com.agent.core.generated.tables.MerchantPlatform;
import com.agent.core.generated.tables.records.MerchantPlatformRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.time.LocalDateTime;
import java.util.List;


/**
 * 商户平台关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MerchantPlatformDao extends DAOImpl<MerchantPlatformRecord, com.agent.core.pojos.MerchantPlatform, ULong> {

    /**
     * Create a new MerchantPlatformDao without any configuration
     */
    public MerchantPlatformDao() {
        super(MerchantPlatform.MERCHANT_PLATFORM, com.agent.core.pojos.MerchantPlatform.class);
    }

    /**
     * Create a new MerchantPlatformDao with an attached configuration
     */
    public MerchantPlatformDao(Configuration configuration) {
        super(MerchantPlatform.MERCHANT_PLATFORM, com.agent.core.pojos.MerchantPlatform.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.agent.core.pojos.MerchantPlatform object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.agent.core.pojos.MerchantPlatform> fetchById(ULong... values) {
        return fetch(MerchantPlatform.MERCHANT_PLATFORM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.agent.core.pojos.MerchantPlatform fetchOneById(ULong value) {
        return fetchOne(MerchantPlatform.MERCHANT_PLATFORM.ID, value);
    }

    /**
     * Fetch records that have <code>merchant_id IN (values)</code>
     */
    public List<com.agent.core.pojos.MerchantPlatform> fetchByMerchantId(String... values) {
        return fetch(MerchantPlatform.MERCHANT_PLATFORM.MERCHANT_ID, values);
    }

    /**
     * Fetch records that have <code>platform_code IN (values)</code>
     */
    public List<com.agent.core.pojos.MerchantPlatform> fetchByPlatformCode(String... values) {
        return fetch(MerchantPlatform.MERCHANT_PLATFORM.PLATFORM_CODE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.agent.core.pojos.MerchantPlatform> fetchByStatus(Integer... values) {
        return fetch(MerchantPlatform.MERCHANT_PLATFORM.STATUS, values);
    }

    /**
     * Fetch records that have <code>CREATED_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.MerchantPlatform> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(MerchantPlatform.MERCHANT_PLATFORM.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.agent.core.pojos.MerchantPlatform> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(MerchantPlatform.MERCHANT_PLATFORM.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.agent.core.pojos.MerchantPlatform> fetchByAppId(String... values) {
        return fetch(MerchantPlatform.MERCHANT_PLATFORM.APP_ID, values);
    }
}
