/*
 * This file is generated by jOOQ.
*/
package com.agent.core.daos;


import com.agent.core.generated.tables.PayeeAccount;
import com.agent.core.generated.tables.records.PayeeAccountRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;


/**
 * 收款账户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayeeAccountDao extends DAOImpl<PayeeAccountRecord, com.agent.core.pojos.PayeeAccount, ULong> {

    /**
     * Create a new PayeeAccountDao without any configuration
     */
    public PayeeAccountDao() {
        super(PayeeAccount.PAYEE_ACCOUNT, com.agent.core.pojos.PayeeAccount.class);
    }

    /**
     * Create a new PayeeAccountDao with an attached configuration
     */
    public PayeeAccountDao(Configuration configuration) {
        super(PayeeAccount.PAYEE_ACCOUNT, com.agent.core.pojos.PayeeAccount.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.agent.core.pojos.PayeeAccount object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>PER_AMOUNT_MIN IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByPerAmountMin(BigInteger... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.PER_AMOUNT_MIN, values);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchById(ULong... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.agent.core.pojos.PayeeAccount fetchOneById(ULong value) {
        return fetchOne(PayeeAccount.PAYEE_ACCOUNT.ID, value);
    }

    /**
     * Fetch records that have <code>ACCOUNT_TYPE IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByAccountType(String... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.ACCOUNT_TYPE, values);
    }

    /**
     * Fetch records that have <code>ACCOUNT_ALIAS IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByAccountAlias(String... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.ACCOUNT_ALIAS, values);
    }

    /**
     * Fetch records that have <code>LOGIN_NO IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByLoginNo(String... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.LOGIN_NO, values);
    }

    /**
     * Fetch records that have <code>DAY_AMOUNT IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByDayAmount(BigInteger... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.DAY_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>PER_AMOUNT IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByPerAmount(BigInteger... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.PER_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>TRADE_INTERVAL IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByTradeInterval(BigInteger... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.TRADE_INTERVAL, values);
    }

    /**
     * Fetch records that have <code>LAST_TRADE_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByLastTradeDate(LocalDateTime... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.LAST_TRADE_DATE, values);
    }

    /**
     * Fetch records that have <code>LOCALE_IP IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByLocaleIp(String... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.LOCALE_IP, values);
    }

    /**
     * Fetch records that have <code>CRAWL_INTERVAL IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByCrawlInterval(BigInteger... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.CRAWL_INTERVAL, values);
    }

    /**
     * Fetch records that have <code>ISDELETED IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByIsdeleted(Integer... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.ISDELETED, values);
    }

    /**
     * Fetch records that have <code>CREATED_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>UPDATE_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>unpay_limit IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByUnpayLimit(Integer... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.UNPAY_LIMIT, values);
    }

    /**
     * Fetch records that have <code>unqrcode_Limit IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByUnqrcodeLimit(Integer... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.UNQRCODE_LIMIT, values);
    }

    /**
     * Fetch records that have <code>MERCHANT_ID IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByMerchantId(String... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.MERCHANT_ID, values);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.agent.core.pojos.PayeeAccount> fetchByAppId(String... values) {
        return fetch(PayeeAccount.PAYEE_ACCOUNT.APP_ID, values);
    }
}
