/*
 * This file is generated by jOOQ.
*/
package com.agent.core.daos;


import com.agent.core.generated.tables.QrcodeUrl;
import com.agent.core.generated.tables.records.QrcodeUrlRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrcodeUrlDao extends DAOImpl<QrcodeUrlRecord, com.agent.core.pojos.QrcodeUrl, Integer> {

    /**
     * Create a new QrcodeUrlDao without any configuration
     */
    public QrcodeUrlDao() {
        super(QrcodeUrl.QRCODE_URL, com.agent.core.pojos.QrcodeUrl.class);
    }

    /**
     * Create a new QrcodeUrlDao with an attached configuration
     */
    public QrcodeUrlDao(Configuration configuration) {
        super(QrcodeUrl.QRCODE_URL, com.agent.core.pojos.QrcodeUrl.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.agent.core.pojos.QrcodeUrl object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchById(Integer... values) {
        return fetch(QrcodeUrl.QRCODE_URL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.agent.core.pojos.QrcodeUrl fetchOneById(Integer value) {
        return fetchOne(QrcodeUrl.QRCODE_URL.ID, value);
    }

    /**
     * Fetch records that have <code>APP_ID IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByAppId(String... values) {
        return fetch(QrcodeUrl.QRCODE_URL.APP_ID, values);
    }

    /**
     * Fetch records that have <code>SERVICE_TYPE IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByServiceType(String... values) {
        return fetch(QrcodeUrl.QRCODE_URL.SERVICE_TYPE, values);
    }

    /**
     * Fetch records that have <code>MERCHANT_NO IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByMerchantNo(String... values) {
        return fetch(QrcodeUrl.QRCODE_URL.MERCHANT_NO, values);
    }

    /**
     * Fetch records that have <code>PAYEE_ACCOUNT IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByPayeeAccount(String... values) {
        return fetch(QrcodeUrl.QRCODE_URL.PAYEE_ACCOUNT, values);
    }

    /**
     * Fetch records that have <code>QRCODE_NUM IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByQrcodeNum(String... values) {
        return fetch(QrcodeUrl.QRCODE_URL.QRCODE_NUM, values);
    }

    /**
     * Fetch a unique record that has <code>QRCODE_NUM = value</code>
     */
    public com.agent.core.pojos.QrcodeUrl fetchOneByQrcodeNum(String value) {
        return fetchOne(QrcodeUrl.QRCODE_URL.QRCODE_NUM, value);
    }

    /**
     * Fetch records that have <code>QRCODE_URL IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByQrcodeUrl(String... values) {
        return fetch(QrcodeUrl.QRCODE_URL.QRCODE_URL_, values);
    }

    /**
     * Fetch records that have <code>AMOUNT IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByAmount(BigInteger... values) {
        return fetch(QrcodeUrl.QRCODE_URL.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByStatus(Integer... values) {
        return fetch(QrcodeUrl.QRCODE_URL.STATUS, values);
    }

    /**
     * Fetch records that have <code>EXPIRE_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByExpireDate(LocalDateTime... values) {
        return fetch(QrcodeUrl.QRCODE_URL.EXPIRE_DATE, values);
    }

    /**
     * Fetch records that have <code>LAST_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByLastDate(LocalDateTime... values) {
        return fetch(QrcodeUrl.QRCODE_URL.LAST_DATE, values);
    }

    /**
     * Fetch records that have <code>NEXT_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByNextDate(LocalDateTime... values) {
        return fetch(QrcodeUrl.QRCODE_URL.NEXT_DATE, values);
    }

    /**
     * Fetch records that have <code>CREATED_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByCreatedDate(LocalDateTime... values) {
        return fetch(QrcodeUrl.QRCODE_URL.CREATED_DATE, values);
    }

    /**
     * Fetch records that have <code>UPDATE_DATE IN (values)</code>
     */
    public List<com.agent.core.pojos.QrcodeUrl> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(QrcodeUrl.QRCODE_URL.UPDATE_DATE, values);
    }
}
